export const monitorHtml = `<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><title>CCDD · Monitor</title><link rel="icon" href="data:,"><link rel="stylesheet" href="/style.css"><script type="module" src="/client.js"></script></head>
<body>
  <header class="app-header"><a class="brand" href="/" aria-label="CCDD Monitor 홈"><span class="brand-mark" aria-hidden="true">c</span><strong>CCDD</strong><span class="brand-divider"></span><span>Monitor</span></a><span id="connection" role="status"><i class="connection-dot"></i><span>연결 중</span></span></header>
  <div class="app-layout">
    <aside class="sidebar"><h2>프로젝트</h2><nav id="projects" aria-label="프로젝트"><p class="muted">불러오는 중…</p></nav></aside>
    <main class="main">
      <section class="request-pane" aria-label="리뷰 요청 목록">
        <div class="page-heading"><div><h1>리뷰 요청</h1><p id="list-caption">진행 상황을 불러오는 중입니다.</p></div><button class="icon-button" id="refresh" aria-label="새로고침" title="새로고침"><svg viewBox="0 0 20 20" fill="none" aria-hidden="true"><path d="M16.3 8A6.5 6.5 0 1 0 16 13M16.5 3.5V8H12" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/></svg></button></div>
        <label class="mobile-project">프로젝트<select id="project-select"><option value="">모든 프로젝트</option></select></label>
        <div class="filters" role="group" aria-label="요청 상태 필터"><button data-filter="all" aria-pressed="true">전체 <span></span></button><button data-filter="active" aria-pressed="false">진행 중 <span></span></button><button data-filter="attention" aria-pressed="false">확인 필요 <span></span></button></div>
        <p id="source-error" class="inline-error" role="status" hidden></p><p id="list-error" class="inline-error" role="alert" hidden></p><div id="requests" class="request-list" aria-live="polite"><div class="empty-state"><span class="loading-dot"></span><p>요청을 불러오는 중…</p></div></div>
        <div class="artifact-pagination"><button id="newer" class="text-button" hidden>최근 요청으로</button><button id="load-more" class="text-button load-more" hidden>이전 요청 보기</button></div>
      </section>
      <section id="detail" class="detail-pane" aria-label="요청 상세" hidden></section>
    </main>
  </div>
</body></html>`;

export const monitorCss = `
:root{font-family:Inter,-apple-system,BlinkMacSystemFont,"Segoe UI","Noto Sans KR",sans-serif;color:#252824;background:#fafbf9;font-size:14px;font-synthesis:none;--muted:#7a7f76;--line:#e7e9e3;--green:#387451;--red:#ac493e;--amber:#96752c}
*{box-sizing:border-box}body{margin:0}button,select,input{font:inherit;color:inherit}button{cursor:pointer}button:disabled{cursor:default;opacity:.5}button,a,input,select,summary{outline-offset:4px}button:focus-visible,a:focus-visible,input:focus-visible,select:focus-visible,summary:focus-visible{outline:2px solid #56876a}button{border:0;background:none}a{color:inherit;text-decoration:none}[hidden]{display:none!important}h1,h2,h3,p{margin:0}svg{width:20px;height:20px;flex-shrink:0}.muted{color:var(--muted)}
.app-header{height:68px;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;padding:0 28px;background:#fff}.brand{display:flex;align-items:center;gap:12px;color:#7b8078;font-size:13px}.brand strong{font-size:16px;letter-spacing:-.6px;color:#2b3028}.brand-mark{width:25px;height:25px;display:grid;place-items:center;color:white;background:#343c31;border-radius:7px;font-size:21px;font-weight:700;line-height:1;padding-bottom:4px}.brand-divider{height:14px;width:1px;background:var(--line);margin:0 2px}#connection{font-size:12px;color:var(--muted);display:flex;align-items:center;gap:7px}.connection-dot{width:6px;height:6px;border-radius:50%;background:#a6ab9f}#connection.connected .connection-dot{background:#589168}#connection.disconnected .connection-dot{background:#b58442}
.app-layout{display:flex;min-height:calc(100svh - 68px)}.sidebar{width:208px;flex-shrink:0;padding:34px 16px;border-right:1px solid var(--line);background:#f5f6f2}.sidebar h2{font-size:11px;color:var(--muted);font-weight:500;letter-spacing:.5px;margin:0 12px 16px}.project-button{display:block;width:100%;text-align:left;padding:11px 12px;border-radius:7px;font-size:13px;margin:2px 0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.project-button:hover{background:#eceee7}.project-button[aria-current=true]{background:#e6eae0;color:#334e36;font-weight:600}.project-button small{display:block;overflow:hidden;text-overflow:ellipsis;font-size:10px;color:var(--muted);margin-top:4px;font-weight:400}.project-separator{border:0;border-top:1px solid var(--line);margin:15px 12px}.project-issue{color:var(--amber);font-size:11px;padding:8px 12px;line-height:1.6}.main{display:flex;flex:1;min-width:0}.request-pane{width:100%;max-width:1080px;padding:38px 44px 40px;margin:0 auto;min-width:0}.main.has-detail .request-pane{max-width:none;width:49%;padding-left:28px;padding-right:28px}.page-heading{display:flex;align-items:center;justify-content:space-between;margin-bottom:27px;gap:16px}h1{font-size:25px;letter-spacing:-1px;font-weight:650}#list-caption{font-size:12px;color:var(--muted);margin-top:8px}.icon-button{display:grid;place-items:center;width:34px;height:34px;border-radius:6px;color:#8b9184}.icon-button:hover{background:#eef0e9;color:#303b2d}.filters{display:flex;gap:4px;padding-bottom:15px;border-bottom:1px solid var(--line)}.filters button{font-size:12px;color:var(--muted);padding:7px 10px;border-radius:6px;white-space:nowrap}.filters button span{margin-left:4px;font-size:11px;font-variant-numeric:tabular-nums}.filters button[aria-pressed=true]{background:#e9ede4;color:#394f35;font-weight:600}.filters button:hover{background:#eef0e9}
.request-row{width:100%;display:flex;align-items:center;gap:16px;text-align:left;padding:20px 12px;border-bottom:1px solid var(--line);border-radius:0;position:relative}.request-row:hover{background:#f2f4ed}.request-row[aria-current=true]{background:#edf1e8}.request-row[aria-current=true]:before{content:"";position:absolute;left:0;top:19px;bottom:19px;width:2px;background:#527a47;border-radius:2px}.request-title{min-width:0;flex:1}.request-title strong{display:block;font-size:14px;font-weight:550;line-height:1.5;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.request-subtitle{display:flex;align-items:center;gap:6px;color:var(--muted);font-size:11px;line-height:1.5;margin-top:7px}.request-subtitle .project-name{max-width:160px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.row-aside{display:flex;align-items:center;justify-content:flex-end;gap:25px}.main.has-detail .row-aside{flex-direction:column;align-items:flex-end;gap:7px}.badge{display:inline-flex;align-items:center;gap:6px;font-size:11px;white-space:nowrap;line-height:1.5;color:#777d71}.badge i{width:5px;height:5px;border-radius:50%;background:currentColor}.badge.running{color:#53799b}.badge.waiting{color:var(--amber)}.badge.green{color:var(--green)}.badge.red,.badge.error{color:var(--red)}.badge.blocked{color:#8c9187}.duration{font-size:11px;color:var(--muted);font-variant-numeric:tabular-nums;min-width:50px;text-align:right}.row-arrow{width:12px;height:12px;color:#aaaFA3}.main.has-detail .row-arrow{display:none}.text-button{font-size:12px;color:#59704f;padding:8px 10px;border-radius:5px}.text-button:hover{background:#edf1e8}.load-more{display:block;margin:22px auto 0}.empty-state{text-align:center;padding:90px 18px;color:var(--muted);font-size:13px;line-height:1.8}.empty-state strong{display:block;font-size:16px;font-weight:500;color:#4c5546;margin-bottom:9px}.empty-state code{background:#edf0e7;border-radius:4px;padding:4px 6px;color:#5b6c51;font-size:12px}.empty-command{margin-top:17px}.empty-hint{margin-top:15px;font-size:11px}.empty-symbol{font-size:30px;font-weight:300;color:#b1baaa;margin-bottom:14px}.loading-dot{display:inline-block;width:6px;height:6px;border-radius:50%;background:#8a987f;margin-bottom:10px}.inline-error{font-size:12px;color:var(--red);line-height:1.7;padding:13px 4px}.mobile-project{display:none}
.detail-pane{width:51%;flex-shrink:0;min-width:0;background:#fff;border-left:1px solid var(--line);height:calc(100svh - 68px);position:sticky;top:0;overflow:auto;padding:27px 34px 44px}.detail-top{display:flex;align-items:center;justify-content:space-between;color:var(--muted);font-size:11px;margin-bottom:24px;gap:12px}.detail-project{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.detail-pane h2{font-size:21px;line-height:1.5;font-weight:600;letter-spacing:-.6px;overflow-wrap:anywhere}.detail-meta{display:flex;flex-wrap:wrap;gap:14px;align-items:center;margin-top:13px;margin-bottom:25px;font-size:11px;color:var(--muted)}.detail-tabs{display:flex;gap:24px;border-bottom:1px solid var(--line);margin-bottom:27px}.detail-tabs button{padding:11px 0;font-size:12px;color:var(--muted);border-bottom:2px solid transparent;margin-bottom:-1px}.detail-tabs button[aria-selected=true]{border-bottom-color:#5c7351;color:#394b30}.outcome{font-size:14px;line-height:1.95;white-space:pre-wrap;overflow-wrap:anywhere}.outcome.error{color:var(--red)}.evidence{margin-top:19px}.evidence summary,.disclosure summary{cursor:pointer;color:#747e6b;font-size:12px;width:fit-content}.evidence ul{padding-left:18px;font-size:12px;line-height:1.9;color:#71796b;overflow-wrap:anywhere}.evidence li+li{margin-top:7px}.detail-section{margin-top:30px;padding-top:25px;border-top:1px solid var(--line)}.section-title{font-size:11px;font-weight:500;color:var(--muted);margin-bottom:17px}.timeline{list-style:none;margin:0;padding:0}.timeline li{display:flex;align-items:center;gap:11px;position:relative;min-height:35px;font-size:12px;color:#65705c}.timeline li:before{content:"";height:5px;width:5px;border-radius:50%;background:#9eab92;flex-shrink:0}.timeline li:not(:last-child):after{content:"";position:absolute;left:2px;top:24px;bottom:-10px;width:1px;background:#e8ece3}.timeline time{margin-left:auto;font-size:11px;color:#919989;font-variant-numeric:tabular-nums}.timeline .step-time{font-size:10px;color:#9fa797;margin-left:3px}.disclosure{margin-top:22px}.instruction{font-size:12px;line-height:1.85;white-space:pre-wrap;overflow-wrap:anywhere;color:#6b7365;margin-top:13px}.profile-description{font-size:11px;color:#8a927f;line-height:1.7;margin-top:15px;overflow-wrap:anywhere}
.artifact-choices{display:flex;flex-wrap:wrap;gap:7px;margin-bottom:22px}.artifact-choice{border:1px solid var(--line);border-radius:5px;padding:7px 10px;color:#727b68;font-size:11px;max-width:100%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.artifact-choice[aria-pressed=true]{background:#f0f3eb;border-color:#ccd7c2;color:#4a633b}.artifact-description{font-size:11px;color:var(--muted);line-height:1.7;margin-bottom:15px}.artifact-toolbar{display:flex;align-items:center;gap:8px;margin-bottom:12px;flex-wrap:wrap}.artifact-path{font-size:11px;color:#66795a;overflow-wrap:anywhere;flex:1}.artifact-back{font-size:11px;color:#687b5c;padding:5px 0;margin-right:5px}.line-jump{display:flex;align-items:center;gap:5px;font-size:10px;color:var(--muted)}.line-jump input{width:63px;border:1px solid var(--line);border-radius:4px;padding:5px 6px;font-size:11px;background:#fff}.line-jump button{font-size:10px;padding:5px}.file-list{border-top:1px solid var(--line)}.file-entry{display:flex;gap:9px;align-items:center;width:100%;padding:12px 3px;border-bottom:1px solid var(--line);font-size:12px;text-align:left;color:#596950}.file-entry:hover{background:#f6f8f2}.file-icon{font-size:14px;color:#9baa8f;flex-shrink:0}.file-name{overflow-wrap:anywhere;min-width:0}.code-view{margin:0;padding:13px 0;border:1px solid var(--line);border-radius:5px;background:#fafbf8;overflow:auto;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:11px;line-height:1.95;tab-size:2;max-height:55svh}.code-line{display:flex;min-height:21px;min-width:max-content;padding-right:15px}.line-number{width:45px;flex-shrink:0;color:#a9b09f;text-align:right;margin-right:14px;user-select:none}.line-content{white-space:pre}.artifact-pagination{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-top:13px;color:var(--muted);font-size:10px}.artifact-message{font-size:12px;line-height:1.8;color:var(--muted);padding:20px 0}.artifact-message.error{color:var(--red)}
@media(min-width:1500px){.main.has-detail .request-pane{width:54%;padding:38px 42px}.detail-pane{width:46%;padding-left:42px;padding-right:42px}}@media(max-width:1150px){.sidebar{width:174px;padding-left:10px;padding-right:10px}.request-pane{padding:30px}.main.has-detail .request-pane{padding:30px 20px;width:47%}.detail-pane{width:53%;padding:25px 24px}.row-aside{gap:15px}.request-row{gap:10px}.filters button{padding:7px 8px}}@media(max-width:950px){.sidebar{display:none}.mobile-project{display:flex;align-items:center;gap:12px;font-size:11px;color:var(--muted);margin-bottom:20px}.mobile-project select{border:1px solid var(--line);background:#fff;padding:6px 9px;border-radius:5px;font-size:12px;max-width:220px}.request-pane{padding:30px}.main.has-detail .request-pane{width:46%;padding:30px 20px}.detail-pane{width:54%}.app-header{padding:0 22px}.request-subtitle .project-name{max-width:105px}}@media(max-width:700px){.app-header{height:58px;padding:0 18px}.brand{gap:9px}.app-layout{min-height:calc(100svh - 58px)}.request-pane{padding:27px 18px;width:100%}.main.has-detail .request-pane{display:none}.detail-pane{width:100%;height:calc(100svh - 58px);border-left:0;padding:22px 23px 40px}h1{font-size:23px}.request-row{padding:19px 7px}.row-aside{flex-direction:column;align-items:flex-end;gap:6px}.row-arrow{display:none}.page-heading{margin-bottom:22px}.empty-state{padding:75px 16px}.timeline time{font-size:10px}.code-view{max-height:52svh}#connection{font-size:11px}}
@media(prefers-reduced-motion:no-preference){.badge.running i{animation:pulse 2s ease-in-out infinite}@keyframes pulse{50%{opacity:.35}}}
`;
